complete -c zen -n "__fish_use_subcommand" -f -a "build" -d "build project from build.zen"
complete -c zen -n "__fish_use_subcommand" -f -a "build-exe" -d "create executable from source or object files"
complete -c zen -n "__fish_use_subcommand" -f -a "build-lib" -d "create library from source or object files"
complete -c zen -n "__fish_use_subcommand" -f -a "build-obj" -d "create object from source or assembly"
complete -c zen -n "__fish_use_subcommand" -f -a "builtin" -d "print compiler builtin source code"
complete -c zen -n "__fish_use_subcommand" -f -a "cc" -d "invoke builtin C compiler"
complete -c zen -n "__fish_use_subcommand" -f -a "fmt" -d "parse files and render in canonical zen format"
complete -c zen -n "__fish_use_subcommand" -f -a "id" -d "print the base64-encoded compiler id"
complete -c zen -n "__fish_use_subcommand" -f -a "init-exe" -d "initialize a `zen build` application in the cwd"
complete -c zen -n "__fish_use_subcommand" -f -a "init-lib" -d "initialize a `zen build` library in the cwd"
complete -c zen -n "__fish_use_subcommand" -f -a "libc" -d "Display native libc paths file or validate one"
complete -c zen -n "__fish_use_subcommand" -f -a "run" -d "create executable and run immediately"
complete -c zen -n "__fish_use_subcommand" -f -a "translate-c" -d "convert C code to Zen code"
complete -c zen -n "__fish_use_subcommand" -f -a "translate-c-2" -d "(exp) self-hosted translate-c"
complete -c zen -n "__fish_use_subcommand" -f -a "targets" -d "list available compilation targets"
complete -c zen -n "__fish_use_subcommand" -f -a "test" -d "create and run a test build"
complete -c zen -n "__fish_use_subcommand" -f -a "version" -d "print version number and exit"
complete -c zen -n "__fish_use_subcommand" -f -a "meditation" -d "find meaning in zen"
complete -c zen -n "__fish_use_subcommand" -f -a "legal" -d "find legal meaning in zen"
